import {database} from '@/db/raw';
import {validateDraft,calculate} from '@/lib/order';
export const dynamic='force-dynamic';
function owner(req:Request){const id=req.headers.get('oai-authenticated-user-id');if(!id)throw new Error('AUTH');return id;}
function fail(e:unknown){const msg=e instanceof Error?e.message:'Không thể lưu. Vui lòng thử lại.';if(msg==='AUTH')return Response.json({error:'Vui lòng đăng nhập để lưu yêu cầu.'},{status:401});console.error('Order API:',msg);return Response.json({error:msg},{status:400});}
export async function GET(req:Request){try{const id=owner(req),db=database();const [o,p]=await Promise.all([db.prepare('SELECT * FROM orders WHERE owner=? ORDER BY created DESC LIMIT 30').bind(id).all(),db.prepare('SELECT payload FROM preferences WHERE owner=?').bind(id).first<{payload:string}>()]);return Response.json({orders:o.results.map((r:any)=>({...r,payload:JSON.parse(r.payload)})),preferences:p?JSON.parse(p.payload):null});}catch(e){return fail(e);}}
export async function POST(req:Request){try{const id=owner(req);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Error('Yêu cầu không hợp lệ.');if(+(req.headers.get('content-length')||0)>16000)throw new Error('Nội dung quá dài.');const raw=await req.text();if(raw.length>16000)throw new Error('Nội dung quá dài.');const b=JSON.parse(raw) as any;const db=database();if(b.action==='order'){if(typeof b.id!=='string'||!/^[a-f0-9-]{36}$/.test(b.id))throw new Error('Mã yêu cầu không hợp lệ.');const draft=validateDraft(b.draft);const total=calculate(draft).total;await db.prepare('INSERT OR IGNORE INTO orders(id,owner,payload,total,status,created) VALUES(?,?,?,?,?,?)').bind(b.id,id,JSON.stringify(draft),total,'pending',new Date().toISOString()).run();const order=await db.prepare('SELECT * FROM orders WHERE id=? AND owner=?').bind(b.id,id).first();if(!order)throw new Error('Không thể lưu yêu cầu.');return Response.json({order:{...order,payload:JSON.parse(order.payload as string)}});}
if(b.action==='update'||b.action==='cancel'||b.action==='accept_demo'){if(!Number.isInteger(b.version))throw new Error('Phiên bản đơn không hợp lệ.');const old=await db.prepare('SELECT * FROM orders WHERE id=? AND owner=?').bind(b.id,id).first<any>();if(!old)throw new Error('Không tìm thấy đơn.');if(old.status!=='pending'||old.version!==b.version)throw new Error('Đơn đã thay đổi hoặc đã được tiếp nhận. Hãy tải lại; không thể tự sửa/hủy.');let payload=old.payload,total=old.total,status=old.status,refund=old.refund;if(b.action==='update'){const d=validateDraft(b.draft);if(d.mode!==JSON.parse(old.payload).mode)throw new Error('Không thể đổi hình thức phục vụ của đơn đã xác nhận.');payload=JSON.stringify(d);total=calculate(d).total;refund=Math.max(0,old.refund+old.total-total);}if(b.action==='cancel'){status='cancelled';refund=old.total+old.refund;}if(b.action==='accept_demo')status='accepted';const result=await db.prepare('UPDATE orders SET payload=?,total=?,status=?,refund=?,version=version+1 WHERE id=? AND owner=? AND status=? AND version=?').bind(payload,total,status,refund,b.id,id,'pending',b.version).run();if(!result.meta.changes)throw new Error('Đơn vừa được thay đổi. Vui lòng tải lại.');return Response.json({ok:true,refund});}
if(b.action==='preferences'){if(b.clear){await db.prepare('DELETE FROM preferences WHERE owner=?').bind(id).run();}else{if(typeof b.text!=='string'||b.text.length>500)throw new Error('Khẩu vị tối đa 500 ký tự.');await db.prepare('INSERT INTO preferences(owner,payload) VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET payload=excluded.payload').bind(id,JSON.stringify({text:b.text,enabled:b.enabled===true})).run();}return Response.json({ok:true});}
if(b.action==='support'||b.action==='feedback'){if(typeof b.text!=='string'||!b.text.trim()||b.text.length>1000)throw new Error('Nhập nội dung tối đa 1.000 ký tự.');const requestId=crypto.randomUUID();await db.prepare('INSERT INTO requests(id,owner,kind,payload,created) VALUES(?,?,?,?,?)').bind(requestId,id,b.action,JSON.stringify({text:b.text,context:b.context?JSON.stringify(b.context).slice(0,5000):'',rating:b.rating}),new Date().toISOString()).run();return Response.json({id:requestId});}throw new Error('Thao tác không hợp lệ.');}catch(e){return fail(e);}}
