export const products = [
  {
    "id": "chickenjoy",
    "name": "1 miếng Gà Giòn Vui Vẻ",
    "price": 33000,
    "currency": "VND",
    "category": "Gà giòn",
    "sourceUrl": "https://jollibee.com.vn/ga-gion.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/1/_/1_mi_ng_ggvv_png_1.png",
    "notes": "1 miếng gà + 1 Tương Chua Ngọt",
    "priceType": "fixed",
    "localImage": "/menu/chickenjoy.png",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "spicy-chicken",
    "name": "1 miếng Gà Sốt Cay",
    "price": 35000,
    "currency": "VND",
    "category": "Gà giòn",
    "sourceUrl": "https://jollibee.com.vn/1-mie-ng-ga-sa-i-go-n-so-t-cay.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/g/_/g_s_t_cay_1.png",
    "notes": "",
    "priceType": "fixed",
    "localImage": "/menu/spicy-chicken.png",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "fries",
    "name": "Khoai tây chiên vừa",
    "price": 20000,
    "currency": "VND",
    "category": "Ăn kèm",
    "sourceUrl": "https://jollibee.com.vn/khoai-tay-v-a.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/p/h/ph_n_n_ph_-_3_4-compressed.jpg",
    "notes": "Khoai tây chiên vừa + 1 Tương Cà",
    "priceType": "fixed",
    "localImage": "/menu/fries.jpg",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "pumpkin-soup",
    "name": "Súp bí đỏ",
    "price": 15000,
    "currency": "VND",
    "category": "Ăn kèm",
    "sourceUrl": "https://jollibee.com.vn/sup-bi-d.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/p/h/ph_n_n_ph_-_5.png",
    "notes": "",
    "priceType": "fixed",
    "localImage": "/menu/pumpkin-soup.png",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "rice",
    "name": "Cơm Trắng",
    "price": 10000,
    "currency": "VND",
    "category": "Ăn kèm",
    "sourceUrl": "https://jollibee.com.vn/com.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/p/h/ph_n_n_ph_-_6.png",
    "notes": "",
    "priceType": "fixed",
    "localImage": "/menu/rice.png",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "peach-mango-pie",
    "name": "Bánh xoài đào",
    "price": 15000,
    "currency": "VND",
    "category": "Tráng miệng",
    "sourceUrl": "https://jollibee.com.vn/banh-xoai-dao.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/m/_/m_n_tr_ng_mi_ng_-_1.png",
    "notes": "",
    "priceType": "fixed",
    "localImage": "/menu/peach-mango-pie.webp",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "tropical-sundae",
    "name": "Tropical Sundae",
    "price": 20000,
    "currency": "VND",
    "category": "Tráng miệng",
    "sourceUrl": "https://jollibee.com.vn/tropical-sundae.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/m/_/m_n_tr_ng_mi_ng_-_2.png",
    "notes": "",
    "priceType": "fixed",
    "localImage": "/menu/tropical-sundae.png",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "strawberry-sundae",
    "name": "Kem Sundae Dâu",
    "price": 15000,
    "currency": "VND",
    "category": "Tráng miệng",
    "sourceUrl": "https://jollibee.com.vn/kem-sundaes-dau.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/m/_/m_n_tr_ng_mi_ng_-_3.png",
    "notes": "",
    "priceType": "fixed",
    "localImage": "/menu/strawberry-sundae.png",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "chocolate-sundae",
    "name": "Kem Sundae Sôcôla",
    "price": 15000,
    "currency": "VND",
    "category": "Tráng miệng",
    "sourceUrl": "https://jollibee.com.vn/kem-sundaes-socola.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/m/_/m_n_tr_ng_mi_ng_-_4.png",
    "notes": "",
    "priceType": "fixed",
    "localImage": "/menu/chocolate-sundae.png",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "spaghetti-drink",
    "name": "1 Mì Ý Jolly vừa + 1 Nước ngọt",
    "price": 40000,
    "currency": "VND",
    "category": "Mì Ý",
    "sourceUrl": "https://jollibee.com.vn/mi-y-so-t-bo-ba-m-nuo-c-ngo-t.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/m/_/m_jolly_-_5-compressed_1.jpg",
    "notes": "Default portion and drink; upgrades cost extra.",
    "priceType": "base_combo",
    "localImage": "/menu/spaghetti-drink.jpg",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "spaghetti-fries-drink",
    "name": "1 Mì Ý Jolly vừa + 1 Khoai tây chiên vừa + 1 Nước ngọt",
    "price": 55000,
    "currency": "VND",
    "category": "Mì Ý",
    "sourceUrl": "https://jollibee.com.vn/mi-y-so-t-bo-ba-m-khoai-tay-vu-a-nuo-c-ngo-t.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/m/_/m_jolly_-_4-compressed_1.jpg",
    "notes": "Includes 1 Tương Cà. Default portion and drink; upgrades cost extra.",
    "priceType": "base_combo",
    "localImage": "/menu/spaghetti-fries-drink.jpg",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  },
  {
    "id": "chicken-rice-drink",
    "name": "1 Cơm Gà Giòn Vui Vẻ + 1 Nước ngọt + 1 Tương Chua Ngọt",
    "price": 53000,
    "currency": "VND",
    "category": "Gà giòn",
    "sourceUrl": "https://jollibee.com.vn/com-ga-gion-nuo-c-ngo-t.html",
    "imageUrl": "https://jollibee.com.vn/media/catalog/product/cache/11f3e6435b23ab624dc55c2d3fe9479d/g/_/g_gi_n_vui_v_-_4.png",
    "notes": "Default portion and drink; upgrades cost extra.",
    "priceType": "base_combo",
    "localImage": "/menu/chicken-rice-drink.webp",
    "downloadStatus": "saved_from_official_image_rendered_in_browser",
    "verifiedVia": "Official product page indexed by web search and official image result",
    "checkedAt": "2026-09-29"
  }
] as const;
export const money=(n:number)=>new Intl.NumberFormat("vi-VN").format(n)+" ₫";
